#!/usr/bin/python

print 
"""
    [Event "##11.14 Ansley Aces"]
    [Site "##"]
    [Date ""]
    [Board "21"]
    [West ""]
    [North ""]
    [East ""]
    [South ""]
    [Dealer "N"]
    [Vulnerable "NS"]
    [Deal "N:K96.AT84.A64.T85 8432.J.T75.AQJ43 AQ7.KQ965.KQ92.9 JT5.732.J83.K762"]
    [Scoring ""]
    [Declarer ""]
    [Contract ""]
    [Result ""] """
